Refactor
principles31/OOP_school_library pull request #5
Opened 2022-08-08 11:43 UTC by principles31

2022-08-08 13:04 UTC, youmari requested changes
Hi @principles31 @yusufnviiri , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ PRO PR
✔️ Git flow 
✔️ Linters passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-08 13:04 UTC, youmari commented on create_student.rb
> +    end
- [ ] It would be better if you extract this code into a separate `method that will be clean and also you will practice the `Single responsibility principle`

2022-08-08 13:04 UTC, youmari commented on create_teacher.rb
> +    specialization = gets.chomp.strip.capitalize
- [ ] It would be better if you extract this code into a separate `method that will be clean and also you will practice the `Single responsibility principle`

2022-08-08 13:04 UTC, youmari commented on create_student.rb
> +    permission = gets.chomp.strip.upcase
- [ ] It would be better if you extract this code into a separate `method that will be clean and also you will practice the `Single responsibility principle`

2022-08-08 19:12 UTC, principles31 commented on create_student.rb
> +    permission = gets.chomp.strip.upcase
@youmari Thank you

2022-08-08 19:16 UTC, principles31 commented
-  It would be better if you extract this code into a separate method that will be clean and also you will practice the Single responsibility principle`
-  It would be better if you extract this code into a separate method that will be clean and also you will practice the Single responsibility principle`
- It would be better if you extract this code into a separate method that will be clean and also you will practice the Single responsibility principle`
- The above changes requested by the previous reviewer has been implemented.

2022-08-08 21:24 UTC, aimemalaika approved these changes
Hi @principles31 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-09 06:58 UTC, principles31 commented
@aimemalaika Thank you for the approval.

2022-08-09 06:58 UTC, merged